### ISSUE TITLE
Less Restrictive License

### ISSUE THREAD

**Issue by martinbu** [humphd/VncSharp#28]
Hi, thanks for this great library. I am looking for a vnc library that can be used in a closed source project. So will there ever be a chance that the license of the VncSharp library will be changed to a less restrictive one, like LGPL, BSD or MIT?

**Comment by SupportingIT** [comment]
I would be really interested in this too, the MIT licence would be great, its open source but is more self contained.

**Comment by Fabzien** [comment]
+1

**Comment by robeving** [comment]
I would love to fork this and invest time in adding new features for the community but the license/my usage means I just can't use it.
LGPL would allow its use as a library.

**Comment by kmscode** [comment]
If I'm not mistaken (and obligatory, IANAL), once a license has been chosen re-licensing it requires the agreement of anyone that has submitted patches to the project. 

If I recall correctly, in the past other projects determined what license they wanted to move to, then notified contributors that the license change will happen unless objections are received within a reasonable amount of time (30ish days). 

I'm OK with a change to LGPL or MIT based on my contributions to this project. I feel that this would be good for the project, as we might get some additional contributions since people could more freely use the code however they want via LGPL/MIT - they might be so kind as to toss any VncSharp fixes back this way, but not have to risk their proprietary code.

@humphd being that this originated with you, obviously we'd have to have your buy-in before moving forward. If you're OK with it, I would think that we should just @[username] tag the other 6 contributors and see if we get their OK or if they forever hold their peace...

**Comment by humphd** [comment]
I think I'd like to stick with GPL, and leave the code as it is.  I'm not looking to make more changes.  Actually, I'm going to archive this repo since I can't handle the constant flood of email I get from people wanting me to fix their code, help them set things up, etc.  I think people assume that it's being worked on, and it's unfair to give that impression. I wrote this code 17 years ago, and haven't even had a Windows machine that can build it for 10+ years :)
